# deploy master branch to gh-pages branch
name: Master Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Setup Git Credentials
        run: |
          git config --global user.email ${{secrets.GITHUB_EMAIL}}
          git config --global user.name  ${{secrets.GITHUB_USERNAME}}

          git remote set-url origin https://${{secrets.GITHUB_USERNAME}}:${{secrets.GITHUB_PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.GITHUB_USERNAME}}/covid19-stats.git

          ssh -T git@github.com
      - name: Deploy to GH Pages
        run: ./deploy.sh
    env:
      CI: true
